name: PR Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          config: '.markdownlint.json'
          globs: '**/*.md'
